version: '3.4'


networks:
    stocKnetwork:


services:
  sqlserverDocker:
    container_name: sql_server_docker
    user: root
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 8006:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=Sql@dmin24
    networks:
    - stocKnetwork
    volumes:
      - database/data:/var/opt/mssql/data
      - database/log:/var/opt/mssql/log
      - database/backup:/var/opt/mssql/backup

  stocksystem:
    image: ${DOCKER_REGISTRY-}stocksystem
    container_name: stockSystem
    build:
      context: .
      dockerfile: stockSystem/Dockerfile
    networks:
    - stocKnetwork
    depends_on:
    - sqlserverDocker
    ports:
    - 5001:8080
  
  stockFrontend:
   image: ${DOCKER_REGISTRY-}stocksystemfrontend
   container_name: stockSystemFrontend
   build:
      context: .
      dockerfile: stockSystemFrontend/Dockerfile
   networks:
    - stocKnetwork
   depends_on:
    - sqlserverDocker
   ports:
    - 80:80


    